import type { Question, LanguageCode, TranslatedQuestion } from './types';

export const quizQuestions: Question[] = [
  // Övergivenhet / Abandonment
  {
    id: 1,
    category: { sv: "Övergivenhet", en: "Abandonment", ar: "الهجر", fi: "Hylkääminen", es: "Abandono", de: "Verlassenheit" },
    categoryCode: "O",
    text: {
      sv: "Hur känner du dig när en nära relation tar slut eller när du är separerad från någon viktig?",
      en: "How do you feel when a close relationship ends or when you are separated from someone important?",
      ar: "كيف تشعر عندما تنتهي علاقة وثيقة أو عندما تكون منفصلاً عن شخص مهم؟",
      fi: "Miltä sinusta tuntuu, kun läheinen suhde päättyy tai olet erossa jostakusta tärkeästä?",
      es: "¿Cómo te sientes cuando una relación cercana termina o cuando estás separado de alguien importante?",
      de: "Wie fühlen Sie sich, wenn eine enge Beziehung endet oder wenn Sie von jemand Wichtigem getrennt sind?",
    },
    options: {
      sv: ["Jag känner mig trygg och kan hantera det bra.", "Jag känner viss oro och har svårt för ensamhet.", "Jag känner djup rädsla och panik för att bli lämnad."],
      en: ["I feel secure and can handle it well.", "I feel some anxiety and have difficulty with loneliness.", "I feel deep fear and panic about being abandoned."],
      ar: ["أشعر بالأمان ويمكنني التعامل مع الأمر بشكل جيد.", "أشعر ببعض القلق وأجد صعوبة في الشعور بالوحدة.", "أشعر بخوف عميق وذعر من أن أُترك."],
      fi: ["Tunnen oloni turvalliseksi ja pystyn käsittelemään sen hyvin.", "Tunnen jonkin verran ahdistusta ja minun on vaikea olla yksin.", "Tunnen syvää pelkoa ja paniikkia hylätyksi tulemisesta."],
      es: ["Me siento seguro y puedo manejarlo bien.", "Siento algo de ansiedad y tengo dificultades con la soledad.", "Siento un profundo miedo y pánico a ser abandonado."],
      de: ["Ich fühle mich sicher und kann gut damit umgehen.", "Ich fühle eine gewisse Angst und habe Schwierigkeiten mit der Einsamkeit.", "Ich empfinde tiefe Angst und Panik davor, verlassen zu werden."],
    },
  },
  {
    id: 2,
    category: { sv: "Övergivenhet", en: "Abandonment", ar: "الهجر", fi: "Hylkääminen", es: "Abandono", de: "Verlassenheit" },
    categoryCode: "O",
    text: {
      sv: "Hur upplever du att vara ensam med dig själv?",
      en: "How do you experience being alone with yourself?",
      ar: "كيف تختبر كونك وحيدًا مع نفسك؟",
      fi: "Miten koet yksin olemisen itsesi kanssa?",
      es: "¿Cómo experimentas estar a solas contigo mismo?",
      de: "Wie erleben Sie es, mit sich allein zu sein?",
    },
    options: {
      sv: ["Jag är bekväm med att vara ensam.", "Jag har svårt att vara ensam under längre perioder.", "Jag har en intensiv rädsla för ensamhet."],
      en: ["I am comfortable being alone.", "I find it difficult to be alone for long periods.", "I have an intense fear of loneliness."],
      ar: ["أنا مرتاح لكوني وحيدًا.", "أجد صعوبة في البقاء وحيدًا لفترات طويلة.", "لدي خوف شديد من الوحدة."],
      fi: ["Olen sinut yksin olemisen kanssa.", "Minun on vaikea olla yksin pitkiä aikoja.", "Minulla on voimakas yksinäisyyden pelko."],
      es: ["Me siento cómodo estando solo.", "Me resulta difícil estar solo por largos períodos.", "Tengo un miedo intenso a la soledad."],
      de: ["Ich bin gerne allein.", "Es fällt mir schwer, über längere Zeiträume allein zu sein.", "Ich habe eine intensive Angst vor der Einsamkeit."],
    },
  },
  {
    id: 3,
    category: { sv: "Övergivenhet", en: "Abandonment", ar: "الهجر", fi: "Hylkääminen", es: "Abandono", de: "Verlassenheit" },
    categoryCode: "O",
    text: {
      sv: "Hur mycket bekräftelse behöver du från andra i dina relationer?",
      en: "How much validation do you need from others in your relationships?",
      ar: "ما مقدار التأكيد الذي تحتاجه من الآخرين في علاقاتك؟",
      fi: "Kuinka paljon vahvistusta tarvitset muilta suhteissasi?",
      es: "¿Cuánta validación necesitas de los demás en tus relaciones?",
      de: "Wie viel Bestätigung benötigen Sie von anderen in Ihren Beziehungen?",
    },
    options: {
      sv: ["Jag känner mig trygg och behöver inte ständig bekräftelse.", "Jag söker ibland bekräftelse för att känna mig trygg.", "Mitt liv domineras av ett konstant behov av bekräftelse."],
      en: ["I feel secure and do not need constant validation.", "I sometimes seek validation to feel secure.", "My life is dominated by a constant need for validation."],
      ar: ["أشعر بالأمان ولا أحتاج إلى تأكيد مستمر.", "أسعى أحيانًا إلى التأكيد لأشعر بالأمان.", "حياتي يهيمن عليها حاجة مستمرة للتأكيد."],
      fi: ["Tunnen oloni turvalliseksi enkä tarvitse jatkuvaa vahvistusta.", "Etsin joskus vahvistusta tunteakseni oloni turvalliseksi.", "Elämääni hallitsee jatkuva vahvistuksen tarve."],
      es: ["Me siento seguro y no necesito validación constante.", "A veces busco validación para sentirme seguro.", "Mi vida está dominada por una necesidad constante de validación."],
      de: ["Ich fühle mich sicher und brauche keine ständige Bestätigung.", "Ich suche manchmal nach Bestätigung, um mich sicher zu fühlen.", "Mein Leben wird von einem ständigen Bedürfnis nach Bestätigung dominiert."],
    },
  },
  // Avvisad / Rejection
  {
    id: 4,
    category: { sv: "Avvisad", en: "Rejection", ar: "الرفض", fi: "Hylkääminen", es: "Rechazo", de: "Ablehnung" },
    categoryCode: "A",
    text: {
      sv: "Hur ofta känner du att du verkligen hör till i sociala sammanhang?",
      en: "How often do you feel you truly belong in social contexts?",
      ar: "كم مرة تشعر أنك تنتمي حقًا في السياقات الاجتماعية؟",
      fi: "Kuinka usein tunnet todella kuuluvasi sosiaalisiin tilanteisiin?",
      es: "¿Con qué frecuencia sientes que realmente perteneces a contextos sociales?",
      de: "Wie oft haben Sie das Gefühl, in sozialen Kontexten wirklich dazuzugehören?",
    },
    options: {
      sv: ["Nästan alltid.", "Ibland känner jag mig ifrågasatt eller utanför.", "Jag har en ständig känsla av att jag inte hör till."],
      en: ["Almost always.", "Sometimes I feel questioned or left out.", "I have a constant feeling that I don't belong."],
      ar: ["دائما تقريبا.", "أحيانًا أشعر بالتشكيك أو الإقصاء.", "لدي شعور دائم بأنني لا أنتمي."],
      fi: ["Melkein aina.", "Joskus tunnen itseni kyseenalaistetuksi tai ulkopuoliseksi.", "Minulla on jatkuva tunne, etten kuulu joukkoon."],
      es: ["Casi siempre.", "A veces me siento cuestionado o excluido.", "Tengo una sensación constante de que no pertenezco."],
      de: ["Fast immer.", "Manchmal fühle ich mich in Frage gestellt oder ausgeschlossen.", "Ich habe ständig das Gefühl, nicht dazuzugehören."],
    },
  },
  {
    id: 5,
    category: { sv: "Avvisad", en: "Rejection", ar: "الرفض", fi: "Hylkääminen", es: "Rechazo", de: "Ablehnung" },
    categoryCode: "A",
    text: {
      sv: "Hur upplever du din roll i en grupp eller ett sammanhang?",
      en: "How do you perceive your role in a group or context?",
      ar: "كيف ترى دورك في مجموعة أو سياق؟",
      fi: "Miten koet roolisi ryhmässä tai kontekstissa?",
      es: "¿Cómo percibes tu papel en un grupo o contexto?",
      de: "Wie nehmen Sie Ihre Rolle in einer Gruppe oder einem Kontext wahr?",
    },
    options: {
      sv: ["Jag känner mig som en välkommen och uppskattad deltagare.", "Jag är ibland orolig för att jag inte är önskad där jag är.", "Jag har en stark, ständig känsla av att jag inte är önskad."],
      en: ["I feel like a welcome and appreciated participant.", "I sometimes worry that I am not wanted where I am.", "I have a strong, constant feeling of not being wanted."],
      ar: ["أشعر بأنني مشارك مرحب به ومقدر.", "أحيانًا أقلق من أنني غير مرغوب فيه حيث أنا.", "لدي شعور قوي ودائم بأنني غير مرغوب فيه."],
      fi: ["Tunnen olevani tervetullut ja arvostettu osallistuja.", "Olen joskus huolissani siitä, etten ole toivottu siellä, missä olen.", "Minulla on vahva, jatkuva tunne, etten ole toivottu."],
      es: ["Me siento como un participante bienvenido y apreciado.", "A veces me preocupa no ser deseado donde estoy.", "Tengo un sentimiento fuerte y constante de no ser deseado."],
      de: ["Ich fühle mich als willkommener und geschätzter Teilnehmer.", "Ich mache mir manchmal Sorgen, dass ich dort, wo ich bin, nicht erwünscht bin.", "Ich habe ein starkes, ständiges Gefühl, nicht gewollt zu sein."],
    },
  },
  {
    id: 6,
    category: { sv: "Avvisad", en: "Rejection", ar: "الرفض", fi: "Hylkääminen", es: "Rechazo", de: "Ablehnung" },
    categoryCode: "A",
    text: {
      sv: "Hur mycket oroar du dig för att bli dömd eller bortvald av andra?",
      en: "How much do you worry about being judged or rejected by others?",
      ar: "ما مدى قلقك من أن يحكم عليك الآخرون أو يرفضونك؟",
      fi: "Kuinka paljon murehdit muiden tuomitsemaksi tai hylkäämäksi tulemista?",
      es: "¿Cuánto te preocupa ser juzgado o rechazado por los demás?",
      de: "Wie sehr machen Sie sich Sorgen, von anderen beurteilt oder abgelehnt zu werden?",
    },
    options: {
      sv: ["Jag har låg social osäkerhet och oroar mig sällan.", "Jag är ibland orolig för vad andra ska tycka om mig.", "Rädslan att bli avvisad styr mycket av hur jag agerar."],
      en: ["I have low social anxiety and rarely worry.", "I am sometimes worried about what others will think of me.", "The fear of rejection heavily influences how I act."],
      ar: ["لدي قلق اجتماعي منخفض ونادرًا ما أقلق.", "أحيانًا أقلق بشأن ما سيفكر فيه الآخرون عني.", "الخوف من الرفض يؤثر بشدة على كيفية تصرفي."],
      fi: ["Minulla on vähän sosiaalista ahdistusta ja huolehdin harvoin.", "Olen joskus huolissani siitä, mitä muut ajattelevat minusta.", "Hylkäämisen pelko vaikuttaa voimakkaasti toimintaani."],
      es: ["Tengo poca ansiedad social y rara vez me preocupo.", "A veces me preocupa lo que los demás pensarán de mí.", "El miedo al rechazo influye mucho en cómo actúo."],
      de: ["Ich habe geringe soziale Ängste und mache mir selten Sorgen.", "Ich mache mir manchmal Sorgen darüber, was andere über mich denken werden.", "Die Angst vor Ablehnung beeinflusst stark, wie ich handle."],
    },
  },
  // Förödmjukad / Humiliation
  {
    id: 7,
    category: { sv: "Förödmjukad", en: "Humiliation", ar: "الإذلال", fi: "Nöyryytys", es: "Humillación", de: "Demütigung" },
    categoryCode: "F",
    text: {
      sv: "Hur skulle du beskriva din självbild?",
      en: "How would you describe your self-image?",
      ar: "كيف تصف صورتك الذاتية؟",
      fi: "Miten kuvailisit minäkuvaasi?",
      es: "¿Cómo describirías tu autoimagen?",
      de: "Wie würden Sie Ihr Selbstbild beschreiben?",
    },
    options: {
      sv: ["Min självbild är stabil och positiv.", "Jag känner mig ibland liten och osäker inför andra.", "Jag plågas av starka skamkänslor och självkritik."],
      en: ["My self-image is stable and positive.", "I sometimes feel small and insecure in front of others.", "I am plagued by strong feelings of shame and self-criticism."],
      ar: ["صورتي الذاتية مستقرة وإيجابية.", "أحيانًا أشعر بالصغر وعدم الأمان أمام الآخرين.", "أعاني من مشاعر قوية بالخزي والنقد الذاتي."],
      fi: ["Minäkuvani on vakaa ja positiivinen.", "Tunnen itseni joskus pieneksi ja epävarmaksi muiden edessä.", "Minua vaivaavat voimakkaat häpeän ja itsekritiikin tunteet."],
      es: ["Mi autoimagen es estable y positiva.", "A veces me siento pequeño e inseguro frente a los demás.", "Me atormentan fuertes sentimientos de vergüenza y autocrítica."],
      de: ["Mein Selbstbild ist stabil und positiv.", "Ich fühle mich manchmal klein und unsicher vor anderen.", "Ich werde von starken Schamgefühlen und Selbstkritik geplagt."],
    },
  },
  {
    id: 8,
    category: { sv: "Förödmjukad", en: "Humiliation", ar: "الإذلال", fi: "Nöyryytys", es: "Humillación", de: "Demütigung" },
    categoryCode: "F",
    text: {
      sv: "Hur reagerar du på misstag eller misslyckanden?",
      en: "How do you react to mistakes or failures?",
      ar: "كيف تتفاعل مع الأخطاء أو الإخفاقات؟",
      fi: "Miten reagoit virheisiin tai epäonnistumisiin?",
      es: "¿Cómo reaccionas ante los errores o fracasos?",
      de: "Wie reagieren Sie auf Fehler oder Misserfolge?",
    },
    options: {
      sv: ["Jag ser dem som tillfällen att lära och utvecklas.", "Jag kan känna mig osäker och självkritisk.", "Jag blir överväldigad av skam och rädsla för att bli avslöjad."],
      en: ["I see them as opportunities to learn and grow.", "I can feel insecure and self-critical.", "I get overwhelmed by shame and fear of being exposed."],
      ar: ["أراها كفرص للتعلم والنمو.", "يمكن أن أشعر بعدم الأمان والنقد الذاتي.", "أشعر بالإرهاق من الخزي والخوف من الانكشاف."],
      fi: ["Näen ne mahdollisuuksina oppia ja kasvaa.", "Voin tuntea itseni epävarmaksi ja itsekriittiseksi.", "Häpeä ja paljastumisen pelko valtaavat minut."],
      es: ["Los veo como oportunidades para aprender y crecer.", "Puedo sentirme inseguro y autocrítico.", "Me siento abrumado por la vergüenza y el miedo a ser expuesto."],
      de: ["Ich sehe sie als Gelegenheiten zum Lernen und Wachsen.", "Ich kann mich unsicher und selbstkritisch fühlen.", "Ich werde von Scham und Angst, aufgedeckt zu werden, überwältigt."],
    },
  },
  {
    id: 9,
    category: { sv: "Förödmjukad", en: "Humiliation", ar: "الإذلال", fi: "Nöyryytys", es: "Humillación", de: "Demütigung" },
    categoryCode: "F",
    text: {
      sv: "Hur mycket oroar du dig för att bli bortgjord eller förnedrad inför andra?",
      en: "How much do you worry about being embarrassed or humiliated in front of others?",
      ar: "ما مدى قلقك من التعرض للإحراج أو الإهانة أمام الآخرين؟",
      fi: "Kuinka paljon murehdit nolatuksi tai nöyryytetyksi tulemisesta muiden edessä?",
      es: "¿Cuánto te preocupa sentirte avergonzado o humillado frente a los demás?",
      de: "Wie sehr machen Sie sich Sorgen, vor anderen blamiert oder gedemütigt zu werden?",
    },
    options: {
      sv: ["Det är inget jag oroar mig för ofta.", "Jag är ibland orolig för vad andra tänker om mig.", "Rädslan för förödmjukelse påverkar starkt mina beslut."],
      en: ["It's not something I worry about often.", "I sometimes worry about what others think of me.", "The fear of humiliation strongly influences my decisions."],
      ar: ["إنه ليس شيئًا أقلق بشأنه كثيرًا.", "أحيانًا أقلق بشأن ما يعتقده الآخرون عني.", "الخوف من الإذلال يؤثر بشدة على قراراتي."],
      fi: ["Se ei ole asia, josta huolehdin usein.", "Olen joskus huolissani siitä, mitä muut ajattelevat minusta.", "Nöyryytyksen pelko vaikuttaa voimakkaasti päätöksiini."],
      es: ["No es algo que me preocupe a menudo.", "A veces me preocupa lo que los demás piensan de mí.", "El miedo a la humillación influye fuertemente en mis decisiones."],
      de: ["Darüber mache ich mir nicht oft Sorgen.", "Ich mache mir manchmal Sorgen darüber, was andere über mich denken.", "Die Angst vor Demütigung beeinflusst meine Entscheidungen stark."],
    },
  },
  // Sviken / Betrayal
  {
    id: 10,
    category: { sv: "Sviken", en: "Betrayal", ar: "الخيانة", fi: "Petos", es: "Traición", de: "Verrat" },
    categoryCode: "S",
    text: {
      sv: "Hur lätt har du att lita på nya människor i ditt liv?",
      en: "How easily do you trust new people in your life?",
      ar: "ما مدى سهولة ثقتك في أشخاص جدد في حياتك؟",
      fi: "Kuinka helposti luotat uusiin ihmisiin elämässäsi?",
      es: "¿Con qué facilidad confías en gente nueva en tu vida?",
      de: "Wie leicht vertrauen Sie neuen Menschen in Ihrem Leben?",
    },
    options: {
      sv: ["Jag har lätt att lita på andra.", "Jag kan vara vaksam i nära relationer och är försiktig.", "Jag har en grundläggande misstro mot andra."],
      en: ["I find it easy to trust others.", "I can be vigilant in close relationships and am cautious.", "I have a fundamental mistrust of others."],
      ar: ["أجد من السهل أن أثق بالآخرين.", "يمكن أن أكون يقظًا في العلاقات الوثيقة وحذرًا.", "لدي عدم ثقة أساسي بالآخرين."],
      fi: ["Minun on helppo luottaa toisiin.", "Voin olla valpas läheisissä suhteissa ja olen varovainen.", "Minulla on perustavanlaatuinen epäluottamus toisia kohtaan."],
      es: ["Me resulta fácil confiar en los demás.", "Puedo ser vigilante en las relaciones cercanas y soy cauteloso.", "Tengo una desconfianza fundamental hacia los demás."],
      de: ["Es fällt mir leicht, anderen zu vertrauen.", "Ich kann in engen Beziehungen wachsam und vorsichtig sein.", "Ich habe ein grundlegendes Misstrauen gegenüber anderen."],
    },
  },
  {
    id: 11,
    category: { sv: "Sviken", en: "Betrayal", ar: "الخيانة", fi: "Petos", es: "Traición", de: "Verrat" },
    categoryCode: "S",
    text: {
      sv: "Hur känner du inför att släppa kontrollen i en relation eller situation?",
      en: "How do you feel about letting go of control in a relationship or situation?",
      ar: "كيف تشعر حيال التخلي عن السيطرة في علاقة أو موقف؟",
      fi: "Miltä sinusta tuntuu päästää irti kontrollista suhteessa tai tilanteessa?",
      es: "¿Cómo te sientes al soltar el control en una relación o situación?",
      de: "Wie fühlen Sie sich dabei, die Kontrolle in einer Beziehung oder Situation loszulassen?",
    },
    options: {
      sv: ["Jag känner mig bekväm med att lita på andra jag har förtroende för.", "Jag kan vara vaksam och känna behov av att vara på min vakt.", "Jag har mycket svårt att släppa kontrollen."],
      en: ["I feel comfortable trusting others I have confidence in.", "I can be vigilant and feel the need to be on my guard.", "I have great difficulty letting go of control."],
      ar: ["أشعر بالراحة في الثقة بالآخرين الذين أثق بهم.", "يمكن أن أكون يقظًا وأشعر بالحاجة إلى توخي الحذر.", "لدي صعوبة كبيرة في التخلي عن السيطرة."],
      fi: ["Tunnen oloni mukavaksi luottaessani ihmisiin, joihin luotan.", "Voin olla valpas ja tuntea tarvetta olla varuillani.", "Minun on erittäin vaikea päästää irti kontrollista."],
      es: ["Me siento cómodo confiando en las personas en las que confío.", "Puedo ser vigilante y sentir la necesidad de estar en guardia.", "Tengo una gran dificultad para soltar el control."],
      de: ["Ich fühle mich wohl dabei, anderen zu vertrauen, denen ich vertraue.", "Ich kann wachsam sein und das Bedürfnis verspüren, auf der Hut zu sein.", "Es fällt mir sehr schwer, die Kontrolle loszulassen."],
    },
  },
  {
    id: 12,
    category: { sv: "Sviken", en: "Betrayal", ar: "الخيانة", fi: "Petos", es: "Traición", de: "Verrat" },
    categoryCode: "S",
    text: {
      sv: "Hur ofta känner du att människor sviker dig eller gör dig besviken?",
      en: "How often do you feel that people betray or disappoint you?",
      ar: "كم مرة تشعر أن الناس يخونونك أو يخيبون أملك؟",
      fi: "Kuinka usein tunnet, että ihmiset pettävät tai tuottavat sinulle pettymyksen?",
      es: "¿Con qué frecuencia sientes que la gente te traiciona o te decepciona?",
      de: "Wie oft haben Sie das Gefühl, dass Menschen Sie verraten oder enttäuschen?",
    },
    options: {
      sv: ["Sällan eller aldrig.", "Ibland känner jag mig sviken, särskilt i nära relationer.", "Jag har en ständig känsla av att jag kommer att bli sviken."],
      en: ["Rarely or never.", "I sometimes feel let down, especially in close relationships.", "I have a constant feeling that I will be betrayed."],
      ar: ["نادرا أو أبدا.", "أحيانًا أشعر بخيبة أمل ، خاصة في العلاقات الوثيقة.", "لدي شعور دائم بأنني سأتعرض للخيانة."],
      fi: ["Harvoin tai ei koskaan.", "Joskus tunnen itseni petetyksi, etenkin läheisissä suhteissa.", "Minulla on jatkuva tunne, että minut petetään."],
      es: ["Rara vez o nunca.", "A veces me siento decepcionado, especialmente en relaciones cercanas.", "Tengo un sentimiento constante de que seré traicionado."],
      de: ["Selten oder nie.", "Manchmal fühle ich mich im Stich gelassen, besonders in engen Beziehungen.", "Ich habe ständig das Gefühl, dass ich betrogen werde."],
    },
  },
  // Orättvisa / Injustice
  {
    id: 13,
    category: { sv: "Orättvisa", en: "Injustice", ar: "الظلم", fi: "Epäoikeudenmukaisuus", es: "Injusticia", de: "Ungerechtigkeit" },
    categoryCode: "R",
    text: {
      sv: "Hur reagerar du på situationer som du uppfattar som orättvisa?",
      en: "How do you react to situations you perceive as unfair?",
      ar: "كيف تتفاعل مع المواقف التي تعتبرها غير عادلة؟",
      fi: "Miten reagoit tilanteisiin, jotka koet epäoikeudenmukaisiksi?",
      es: "¿Cómo reaccionas ante situaciones que percibes como injustas?",
      de: "Wie reagieren Sie auf Situationen, die Sie als unfair empfinden?",
    },
    options: {
      sv: ["Jag kan acceptera att livet inte alltid är rättvist.", "Jag kan reagera starkt och känna mig frustrerad.", "Jag känner intensiv vrede och en stark känsla av maktlöshet."],
      en: ["I can accept that life is not always fair.", "I can react strongly and feel frustrated.", "I feel intense anger and a strong sense of powerlessness."],
      ar: ["يمكنني أن أقبل أن الحياة ليست عادلة دائمًا.", "يمكن أن أتفاعل بقوة وأشعر بالإحباط.", "أشعر بغضب شديد وشعور قوي بالعجز."],
      fi: ["Voin hyväksyä, että elämä ei ole aina reilua.", "Voin reagoida voimakkaasti ja tuntea turhautumista.", "Tunnen voimakasta vihaa ja suurta voimattomuuden tunnetta."],
      es: ["Puedo aceptar que la vida no siempre es justa.", "Puedo reaccionar fuertemente y sentirme frustrado.", "Siento una ira intensa y un fuerte sentimiento de impotencia."],
      de: ["Ich kann akzeptieren, dass das Leben nicht immer fair ist.", "Ich kann stark reagieren und mich frustriert fühlen.", "Ich empfinde intensive Wut und ein starkes Gefühl der Ohnmacht."],
    },
  },
  {
    id: 14,
    category: { sv: "Orättvisa", en: "Injustice", ar: "الظلم", fi: "Epäoikeudenmukaisuus", es: "Injusticia", de: "Ungerechtigkeit" },
    categoryCode: "R",
    text: {
      sv: "Hur ofta känner du att du har blivit orättvist behandlad?",
      en: "How often do you feel you have been treated unfairly?",
      ar: "كم مرة تشعر أنك عوملت بشكل غير عادل؟",
      fi: "Kuinka usein sinusta tuntuu, että sinua on kohdeltu epäoikeudenmukaisesti?",
      es: "¿Con qué frecuencia sientes que has sido tratado injustamente?",
      de: "Wie oft haben Sie das Gefühl, ungerecht behandelt worden zu sein?",
    },
    options: {
      sv: ["Sällan eller aldrig.", "Ibland känner jag att jag har blivit orättvist behandlad.", "Känslan av orättvisa konsumerar mig ofta."],
      en: ["Rarely or never.", "I sometimes feel I have been treated unfairly.", "The feeling of injustice often consumes me."],
      ar: ["نادرا أو أبدا.", "أحيانًا أشعر أنني عوملت بشكل غير عادل.", "غالبًا ما يستهلكني الشعور بالظلم."],
      fi: ["Harvoin tai ei koskaan.", "Joskus tunnen, että minua on kohdeltu epäoikeudenmukaisesti.", "Epäoikeudenmukaisuuden tunne kuluttaa minut usein."],
      es: ["Rara vez o nunca.", "A veces siento que he sido tratado injustamente.", "El sentimiento de injusticia a menudo me consume."],
      de: ["Selten oder nie.", "Manchmal habe ich das Gefühl, ungerecht behandelt worden zu sein.", "Das Gefühl der Ungerechtigkeit verzehrt mich oft."],
    },
  },
  {
    id: 15,
    category: { sv: "Orättvisa", en: "Injustice", ar: "الظلم", fi: "Epäoikeudenmukaisuus", es: "Injusticia", de: "Ungerechtigkeit" },
    categoryCode: "R",
    text: {
      sv: "Vad är din allmänna inställning till rättvisa?",
      en: "What is your general attitude towards justice?",
      ar: "ما هو موقفك العام تجاه العدالة؟",
      fi: "Mikä on yleinen asenteesi oikeudenmukaisuuteen?",
      es: "¿Cuál es tu actitud general hacia la justicia?",
      de: "Was ist Ihre allgemeine Einstellung zur Gerechtigkeit?",
    },
    options: {
      sv: ["Jag uppskattar rättvisa men kan acceptera brister.", "Jag är passionerad om rättvisa och blir upprörd när den saknas.", "Jag har ett starkt rättvisepatos som ofta leder till vrede när jag bevittnar orättvisor."],
      en: ["I appreciate justice but can accept imperfections.", "I am passionate about justice and get upset when it is lacking.", "I have a strong sense of justice that often leads to anger when I witness injustices."],
      ar: ["أقدر العدالة ولكن يمكنني قبول العيوب.", "أنا متحمس للعدالة وأنزعج عندما تكون مفقودة.", "لدي شعور قوي بالعدالة غالبًا ما يؤدي إلى الغضب عندما أشهد الظلم."],
      fi: ["Arvostan oikeudenmukaisuutta, mutta voin hyväksyä puutteet.", "Olen intohimoinen oikeudenmukaisuudesta ja suutun, kun sitä puuttuu.", "Minulla on vahva oikeudentunto, joka usein johtaa vihaan, kun todistan epäoikeudenmukaisuuksia."],
      es: ["Aprecio la justicia pero puedo aceptar imperfecciones.", "Me apasiona la justicia y me molesto cuando falta.", "Tengo un fuerte sentido de la justicia que a menudo me lleva a la ira cuando presencio injusticias."],
      de: ["Ich schätze Gerechtigkeit, kann aber Unvollkommenheiten akzeptieren.", "Ich bin leidenschaftlich für Gerechtigkeit und werde wütend, wenn sie fehlt.", "Ich habe einen starken Gerechtigkeitssinn, der oft zu Wut führt, wenn ich Ungerechtigkeiten sehe."],
    },
  },
  // Ensamhet / Loneliness
  {
    id: 16,
    category: { sv: "Ensamhet", en: "Loneliness", ar: "الوحدة", fi: "Yksinäisyys", es: "Soledad", de: "Einsamkeit" },
    categoryCode: "E",
    text: {
      sv: "Hur ser du på att tillbringa tid ensam, utan sällskap?",
      en: "How do you view spending time alone, without company?",
      ar: "كيف تنظر إلى قضاء الوقت بمفردك ، بدون رفقة؟",
      fi: "Miten suhtaudut yksin vietettyyn aikaan, ilman seuraa?",
      es: "¿Cómo ves pasar tiempo a solas, sin compañía?",
      de: "Wie sehen Sie es, Zeit allein zu verbringen, ohne Gesellschaft?",
    },
    options: {
      sv: ["Jag känner mig bekväm och lugn med att vara ensam.", "Jag kan hantera ensamhet, men föredrar ofta att ha sällskap.", "Jag känner en djup obehagskänsla och ångest när jag är ensam."],
      en: ["I feel comfortable and calm being alone.", "I can handle loneliness, but often prefer company.", "I feel a deep sense of discomfort and anxiety when I am alone."],
      ar: ["أشعر بالراحة والهدوء عندما أكون وحدي.", "يمكنني التعامل مع الوحدة ، لكنني غالبًا ما أفضل الرفقة.", "أشعر بإحساس عميق بعدم الراحة والقلق عندما أكون وحدي."],
      fi: ["Tunnen oloni mukavaksi ja rauhalliseksi ollessani yksin.", "Pärjään yksinäisyyden kanssa, mutta pidän usein seurasta.", "Tunnen syvää epämukavuutta ja ahdistusta ollessani yksin."],
      es: ["Me siento cómodo y tranquilo estando solo.", "Puedo manejar la soledad, pero a menudo prefiero la compañía.", "Siento una profunda sensación de incomodidad y ansiedad cuando estoy solo."],
      de: ["Ich fühle mich wohl und ruhig, wenn ich allein bin.", "Ich kann mit Einsamkeit umgehen, bevorzuge aber oft Gesellschaft.", "Ich empfinde ein tiefes Gefühl des Unbehagens und der Angst, wenn ich allein bin."],
    },
  },
  {
    id: 17,
    category: { sv: "Ensamhet", en: "Loneliness", ar: "الوحدة", fi: "Yksinäisyys", es: "Soledad", de: "Einsamkeit" },
    categoryCode: "E",
    text: {
      sv: "Hur mycket känner du att du behöver andras närvaro för att känna dig hel och trygg?",
      en: "How much do you feel you need others' presence to feel whole and secure?",
      ar: "إلى أي مدى تشعر أنك بحاجة إلى وجود الآخرين لتشعر بالكمال والأمان؟",
      fi: "Kuinka paljon tunnet tarvitsevasi muiden läsnäoloa tunteaksesi itsesi kokonaiseksi ja turvalliseksi?",
      es: "¿Cuánto sientes que necesitas la presencia de otros para sentirte completo y seguro?",
      de: "Wie sehr haben Sie das Gefühl, die Anwesenheit anderer zu brauchen, um sich ganz und sicher zu fühlen?",
    },
    options: {
      sv: ["Jag känner mig trygg och hel i mig själv, oavsett andras närvaro.", "Jag kan känna en viss oro och att jag behöver andras närvaro för att känna mig trygg.", "Jag känner mig tom och plågsamt ensam när jag inte har någon annans närvaro."],
      en: ["I feel secure and whole in myself, regardless of others' presence.", "I can feel some anxiety and need others' presence to feel secure.", "I feel empty and painfully lonely when I don't have someone else's presence."],
      ar: ["أشعر بالأمان والاكتمال في نفسي ، بغض النظر عن وجود الآخرين.", "يمكن أن أشعر ببعض القلق وأحتاج إلى وجود الآخرين لأشعر بالأمان.", "أشعر بالفراغ والوحدة المؤلمة عندما لا يكون لدي وجود شخص آخر."],
      fi: ["Tunnen oloni turvalliseksi ja kokonaiseksi itsessäni, riippumatta muiden läsnäolosta.", "Voin tuntea jonkin verran ahdistusta ja tarvita muiden läsnäoloa tunteakseni oloni turvalliseksi.", "Tunnen itseni tyhjäksi ja tuskallisen yksinäiseksi, kun minulla ei ole jonkun toisen läsnäoloa."],
      es: ["Me siento seguro y completo en mí mismo, independientemente de la presencia de otros.", "Puedo sentir algo de ansiedad y necesitar la presencia de otros para sentirme seguro.", "Me siento vacío y dolorosamente solo cuando no tengo la presencia de otra persona."],
      de: ["Ich fühle mich in mir selbst sicher und ganz, unabhängig von der Anwesenheit anderer.", "Ich kann eine gewisse Angst verspüren und die Anwesenheit anderer brauchen, um mich sicher zu fühlen.", "Ich fühle mich leer und schmerzlich einsam, wenn ich nicht die Anwesenheit eines anderen habe."],
    },
  },
  {
    id: 18,
    category: { sv: "Ensamhet", en: "Loneliness", ar: "الوحدة", fi: "Yksinäisyys", es: "Soledad", de: "Einsamkeit" },
    categoryCode: "E",
    text: {
      sv: "Hur ofta upplever du en känsla av djup ensamhet, även när du är omgiven av andra?",
      en: "How often do you experience a feeling of deep loneliness, even when surrounded by others?",
      ar: "كم مرة تشعر بشعور عميق بالوحدة ، حتى عندما تكون محاطًا بالآخرين؟",
      fi: "Kuinka usein koet syvän yksinäisyyden tunteen, vaikka olisit muiden ympäröimänä?",
      es: "¿Con qué frecuencia experimentas un sentimiento de profunda soledad, incluso cuando estás rodeado de otros?",
      de: "Wie oft empfinden Sie ein Gefühl tiefer Einsamkeit, selbst wenn Sie von anderen umgeben sind?",
    },
    options: {
      sv: ["Sällan eller aldrig.", "Ibland kan jag känna mig ensam, trots att jag är med andra.", "Jag har en ständig känsla av ensamhet som är svår att fylla."],
      en: ["Rarely or never.", "I can sometimes feel lonely, even when I'm with others.", "I have a constant feeling of loneliness that is hard to fill."],
      ar: ["نادرا أو أبدا.", "يمكنني أحيانًا أن أشعر بالوحدة ، حتى عندما أكون مع الآخرين.", "لدي شعور دائم بالوحدة يصعب ملؤه."],
      fi: ["Harvoin tai ei koskaan.", "Voin joskus tuntea itseni yksinäiseksi, vaikka olisinkin muiden kanssa.", "Minulla on jatkuva yksinäisyyden tunne, jota on vaikea täyttää."],
      es: ["Rara vez o nunca.", "A veces puedo sentirme solo, incluso cuando estoy con otros.", "Tengo un sentimiento constante de soledad que es difícil de llenar."],
      de: ["Selten oder nie.", "Manchmal kann ich mich einsam fühlen, auch wenn ich mit anderen zusammen bin.", "Ich habe ein ständiges Gefühl der Einsamkeit, das schwer zu füllen ist."],
    },
  },
];

export const getTranslatedQuestions = (lang: LanguageCode): TranslatedQuestion[] => {
  return quizQuestions.map(q => ({
    id: q.id,
    category: q.category[lang] || q.category['sv']!,
    categoryCode: q.categoryCode,
    text: q.text[lang] || q.text['sv']!,
    options: q.options[lang] || q.options['sv']!,
  }));
};
